import {
  ArchiveRestore,
  Award,
  BadgeCheck,
  BadgeHelp,
  Bell,
  Camera,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  ClipboardCopy,
  Download,
  FileBadge,
  FileInput,
  FileOutput,
  LucideFolderArchive,
  MessageSquareMore,
  Power,
  QrCode,
  RefreshCcw,
  Share2,
  Star,
  SwitchCamera,
} from "lucide-react-native";

import { iconWithClassName } from "./iconWithClassName";
iconWithClassName(Award);
iconWithClassName(ChevronRight);
iconWithClassName(FileBadge);
iconWithClassName(Camera);
iconWithClassName(CircleCheckBig);
iconWithClassName(ArchiveRestore);
iconWithClassName(ClipboardCopy);
iconWithClassName(LucideFolderArchive);
iconWithClassName(Star);
iconWithClassName(Download);
iconWithClassName(Share2);
iconWithClassName(Power);
iconWithClassName(RefreshCcw);
iconWithClassName(SwitchCamera);
iconWithClassName(QrCode);
iconWithClassName(MessageSquareMore);
iconWithClassName(ChevronLeft);
iconWithClassName(Bell);
iconWithClassName(BadgeCheck);
iconWithClassName(BadgeHelp);
iconWithClassName(FileInput);
iconWithClassName(FileOutput);

export {
  ArchiveRestore,
  Award,
  BadgeCheck,
  BadgeHelp,
  Bell,
  Camera,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  ClipboardCopy,
  Download,
  FileBadge,
  FileInput,
  FileOutput,
  LucideFolderArchive,
  MessageSquareMore,
  Power,
  QrCode,
  RefreshCcw,
  Share2,
  Star,
  SwitchCamera,
};
